# Generated by Django 4.2.1 on 2023-10-08 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Barbearia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "cnpj",
                    models.CharField(
                        default=None, max_length=14, unique=True, verbose_name="CNPJ"
                    ),
                ),
                ("endereco", models.CharField(max_length=150, verbose_name="Endereço")),
                ("telefone", models.CharField(max_length=150, verbose_name="Telefone")),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dono",
                    ),
                ),
            ],
        ),
    ]
