# Generated by Django 4.2.5 on 2023-10-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Logo'),
        ),
    ]
