# Generated by Django 4.2.5 on 2023-12-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='descricao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição'),
        ),
    ]
