# Generated by Django 4.2.5 on 2023-10-31 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbeiros',
            name='barbearia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearia.barbearia', verbose_name='Barbearia'),
        ),
    ]
