# Generated by Django 4.2.5 on 2023-11-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento'),
        ),
    ]
