# Generated by Django 4.2.5 on 2023-11-21 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("barbearia", "0002_alter_barbearia_logo"),
        ("barbearia", "0002_barbearia_complemento"),
        ("barbearia", "0002_initial"),
    ]

    operations = []
