# Generated by Django 4.2.5 on 2023-11-21 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0002_alter_barbearia_logo'),
        ('barbearia', '0002_initial'),
    ]

    operations = [
    ]
