# Generated by Django 4.2.1 on 2023-10-18 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("barbearia", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="barbearia",
            options={"verbose_name": "Barbearia", "verbose_name_plural": "Barbearias"},
        ),
        migrations.AlterField(
            model_name="barbearia",
            name="dono",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dono",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="barbearia",
            unique_together={("cnpj", "dono")},
        ),
    ]
