# Generated by Django 4.2.5 on 2023-11-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0003_merge_0002_alter_barbearia_logo_0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Logo'),
        ),
    ]
