# Generated by Django 4.2.1 on 2023-11-20 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("barbearia", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horarios_funcionamento", models.JSONField(blank=True)),
                (
                    "barbearia",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="barbearia.barbearia",
                        verbose_name="Barbeiro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=50, verbose_name="Nome do Serviço"),
                ),
                (
                    "tempo_servico",
                    models.IntegerField(verbose_name="Tempo 'médio' do serviço"),
                ),
                (
                    "medida_tempo",
                    models.IntegerField(
                        choices=[(1, "Minutos"), (2, "Horas")],
                        verbose_name="Medida de Tempo",
                    ),
                ),
                (
                    "barbearia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="barbearia.barbearia",
                        verbose_name="Barbearia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                ("hora_fim", models.TimeField(default=None)),
                ("aprovado", models.BooleanField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now=True)),
                (
                    "agenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agendamento.agenda",
                        verbose_name="Agenda",
                    ),
                ),
                (
                    "barbeiro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="barbeiro",
                        to="barbearia.barbeiros",
                        verbose_name="Barbeiro",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agendamento.servico",
                        verbose_name="Servico",
                    ),
                ),
            ],
        ),
    ]
