# Generated by Django 4.2.5 on 2023-11-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios_funcionamento', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('hora_fim', models.TimeField(default=None)),
                ('aprovado', models.BooleanField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('modificado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do Serviço')),
                ('tempo_servico', models.IntegerField(verbose_name="Tempo 'médio' do serviço")),
                ('medida_tempo', models.IntegerField(choices=[(1, 'Minutos'), (2, 'Horas')], verbose_name='Medida de Tempo')),
            ],
        ),
    ]
