# Generated by Django 4.2.1 on 2023-10-24 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agendamento", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agenda",
            name="horarios_intervalo",
        ),
    ]
