# Generated by Django 4.2.5 on 2023-10-31 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
        ('barbearia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='barbearia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearia.barbearia', verbose_name='Barbearia'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agenda', verbose_name='Agenda'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='barbeiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbeiro', to='barbearia.barbeiros', verbose_name='Barbeiro'),
        ),
    ]
