# Generated by Django 4.2.1 on 2023-10-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("barbearia", "0001_initial"),
        ("agendamento", "0002_remove_agenda_horarios_intervalo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="barbearia",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="barbearia.barbearia",
                verbose_name="Barbeiro",
            ),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="horarios_funcionamento",
            field=models.JSONField(blank=True),
        ),
    ]
