# Generated by Django 4.2.5 on 2023-10-31 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barbearia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.servico', verbose_name='Servico'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='barbearia',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='barbearia.barbearia', verbose_name='Barbeiro'),
        ),
    ]
