# Generated by Django 4.2.5 on 2023-10-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0001_initial'),
        ('agendamento', '0003_alter_agenda_barbearia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='barbearia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearia.barbearia', verbose_name='Barbearia'),
        ),
    ]
