# Generated by Django 4.2.5 on 2023-10-30 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_servico_barbearia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agenda', verbose_name='Agenda'),
        ),
    ]
