version: "3"

services:
  db:
    image: postgres:latest

  web:
    build: ./
    command: bash -c "python manage.py migrate && python manage.py makemigrations && gunicorn --bind 0.0.0.0:8000 barberease.wsgi:application"
    container_name: barberease
    volumes:
      - .:/barberease
    ports:
      - "8000:8000"
    depends_on:
      - db
