version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      POSTGRES_HOST: pg-ckil53212bvs739uphc0-a.ohio-postgres.render.com
      POSTGRES_USER: barbereaseadmin
      POSTGRES_DB: db_barberease_xjlp
      POSTGRES_PASSWORD: LPoHNUCoR9l6RpSIX7v4bV08BqNFBB42

  web:
    build: ./
    command: bash -c "python manage.py migrate && python manage.py makemigrations && gunicorn --bind 0.0.0.0:8000 barberease.wsgi:application"
    container_name: barberease
    volumes:
      - .:/barberease
    ports:
      - "8000:8000"
    depends_on:
      - db
  - image: render/basic:1
    instances: 1
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "barberease.settings"  
      - key: DATABASE_URL
        fromDatabase: db_barberease  
    ports:
      - port: 8000
        protocol: TCP

  - image: nginx:latest
    automaticScaling:
      minInstances: 1
      maxInstances: 10
    ports:
      - port: 80
        protocol: TCP
