version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST: dpg-ckes65vs0fgc73caqeig-a.oregon-postgres.render.com
      POSTGRES_USER: barbereaseadmin
      POSTGRES_DB: db_barberease_r7co
      POSTGRES_PASSWORD: ndUpySdlwCGYBfXDVgPiy3bs7HiUoDUT
  web:
    build: ./
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: barberease
    volumes:
      - .:/barberease
    ports:
      - "8000:8000"
    depends_on:
      - db
