version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST: pg-ckil53212bvs739uphc0-a.ohio-postgres.render.com
      POSTGRES_USER: barbereaseadmin
      POSTGRES_DB: db_barberease_xjlp
      POSTGRES_PASSWORD: LPoHNUCoR9l6RpSIX7v4bV08BqNFBB42
  web:
    build: ./
    command: bash -c "gunicorn --bind :8000 --workers 3 barberease.wsgi:application"
    container_name: barberease
    volumes:
      - .:/barberease
    ports:
      - "8000:8000"
    depends_on:
      - db
