# Generated by Django 4.2.1 on 2023-10-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="sobrenome",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Sobrenome"
            ),
        ),
    ]
