# Generated by Django 4.2.5 on 2023-11-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='logo',
        ),
    ]
