# Generated by Django 4.2.1 on 2023-11-20 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="logo",
        ),
    ]
